[project]
name = "helix-api"
version = "0.1.0"
description = "HelixAI FastAPI application"
authors = [
    { name = "Ebunwadi", email = "111129501+Ebunwadi@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
helix-api = "helix_api:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
